pull_request_rules:

  - name: Trigger an auto-rebase workflow
    conditions:
      - or:
        - label=auto-update-rebase
        - and:
            - label=dependencies
            - or: &authors_are_bots
                - author=renovate[bot]
                - author=dependabot[bot]
      - -draft
      - -conflict
    actions:
      comment:
        message: |
          /rebase

  - name: Auto-update with merge if appropriately labeled
    conditions:
      - label=auto-update-merge
      - -draft
      - -conflict
    actions:
      update:

  - name: rebase-merge working updates
    conditions:
      - or: *authors_are_bots
      - "#review-threads-unresolved=0"
      - "#commits-behind=0"
      - label=dependencies
      - -draft
      - -conflict
    actions:
      merge:
        method: rebase

  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: |
          Hi @{{author}}! :wave:
          This pull request has conflicts :confounded:
          Could you fix it? :wrench:
          Thank you! :pray: