on:
  issue_comment:
    types: [created]

jobs:
  check-for-rebase:
    uses: DanySK/workflows/.github/workflows/rebase-on-comment.yml@7390230b68b6ed20fced7c5abf6d2f2c00e3aa61
    with:
      token: ${{ secrets.WORKFLOW_TOKEN }}
